### ISSUE TITLE
How can upgrade to jwplayer version 7 with ALLVIDEO plugin.

### ISSUE THREAD

**Issue by goodtaste** [joomlaworks/allvideos#16]
JW Player 7 is faster and smarter than the previous version. They've also removed their watermark from the free version and allowed you to include your own branding.

**Comment by studio4am** [comment]
It's really simple. You just need to download JW Player 7, extract, then replace jwplayer.flash.swf and jwplayer.js.
Now grab your license key from your account at JW's website, add the following code to your template, with your info:
[code]<script src="http://mywebsite.com/jwplayer/jwplayer.js"></script>
<script>jwplayer.key="ABCdeFG123456SeVenABCdeFG123456SeVen==";</script>[/code]

More info here: http://support.jwplayer.com/customer/portal/articles/1406723-basic-video-embed#option-3-self-host

**Comment by fevangelou** [comment]
AllVideos is loading the JW Player over its CDN by default so you always have the latest version...

**Comment by studio4am** [comment]
Actually, it's not by default, at least not on my two installations. The CDN option was disabled on both. Still though, the option is there. But there's more than that now because JW now requires a license for the free version. So even if you select it, you need to license it and add the script. This is something AllVideos should address in their next update: Include the script and give the ability to enter your license code.

**Comment by fevangelou** [comment]
It's there already. Check the latest version. The license option is in the "advanced" tab.

**Comment by fevangelou** [comment]
Looking again at the new v7 setup of the player, they may use custom URLs for the .js link.

I'll update AllVideos accordingly.

**Comment by studio4am** [comment]
Exactly, fevangelou... they do. Now they require free users to create a player and use that custom url. Also, JW 7 requires the script for self hosting:
​<script src="http://mywebsite.com/jwplayer/jwplayer.js"></script>
<script>jwplayer.key="ABCdeFG123456SeVenABCdeFG123456SeVen==";</script>

... but I'm sure with an AllVideos update, that'll be solved.

Thank you very much for your attention :)

**Comment by baijianpeng** [comment]
I tested with Allvideos plugin v4.7.0, after I replaced the whole jwplayer folder with files form JW Player official website (v7.2.4), then I input my own Licence Key from JW Player account, but Allvideos plugin did not render the player, instead, it shows following error message:

`Error setting up player: Invalid license key`

Hope you will upgrade this plugin with JW Player v7 and allow to use License Key to hide the watermark.

**Comment by edgecity13** [comment]
I got a JW 7 license, copied the JW 7 player into the plugin folder, configured the plugin and was able to get audio and video to play. The responsive template doesn't work though. audio players are truncated horizontally. video players expand to the full width even when a smaller width is specified in the plugin, and the video overflows the frame so only part of the content is displayed. I see fevangelou was going to look into JW 7 setup on 11/16/2015.  Can any update on this issue be offered? thanks.

**Comment by edgecity13** [comment]
I was able to get All Videos working responsively with JW 7. I copied the Beelden template CSS and created the same file structure allvideos is expecting, see attached zip. I added the CSS default.php is expecting, tweaked it and it worked. Not tested thoroughly but I think it's close. What would it take to get this to the next step and get the very patient k2/AV community a new release?
[Beelden.zip](https://github.com/joomlaworks/allvideos/files/683722/Beelden.zip)

**Comment by fevangelou** [comment]
AllVideos v4.8.0 with JW Player v7 and Clappr as the new default video player is coming this Monday. The demo site already features v4.8.0 and you can try it now by getting the latest snapshot from this GitHub repo: https://github.com/joomlaworks/allvideos/archive/master.zip
