### ISSUE TITLE
Error in Joomla! tags view

### ISSUE THREAD

**Issue by kavadas** [joomlaworks/allvideos#18]
The plugin is causing a fatal error when a link to the Joomla! tags component is created. Solution at http://www.joomlaworks.net/forum/allvideos/42999-error-in-joomla-tag-page?start=10#147764

**Comment by kavadas** [comment]
The final working solution, verified by the forum members can be found at http://www.joomlaworks.net/forum/allvideos/42999-error-in-joomla-tag-page?start=20#147830

**Comment by fevangelou** [comment]
Fixed in https://github.com/joomlaworks/allvideos/commit/e6a7569a90abba3adf312d948aaf8001660fca37
