### ISSUE TITLE
Rename AC_QuickTime.js to ac_quicktime.js

### ISSUE THREAD

**Issue by kavadas** [joomlaworks/allvideos#19]
Different letter case creates several issues such as 
http://www.joomlaworks.net/forum/allvideos/43157-php-warnings#147986

**Comment by fevangelou** [comment]
The filenames & paths are correct on the latest version. Maybe that was an old release.

**Comment by kavadas** [comment]
No, they are not. The latest stable package contains the file named like AC_QuickTime.js instead of ac_quicktime.js . The code is requesting the file as ac_quicktime.js .

**Comment by fevangelou** [comment]
You're write. It's not in the release zip file, but it's already corrected in the repo.

**Comment by htmgarcia** [comment]
I can confirm that renaming to AC_QuickTime.js fix the issue in 4.7.0 version

**Comment by htmgarcia** [comment]
@kavadas is right!
