### ISSUE TITLE
Mootools 

### ISSUE THREAD

**Issue by kavadas** [joomlaworks/allvideos#20]
It seems that the plugin is loading Mootools but it's not using it. Here is the issue at the forum http://www.joomlaworks.net/forum/allvideos/43259-allvideos-loads-mootools#148120 .

**Comment by fevangelou** [comment]
This was originally used to make sure the JW Player .js files are loaded after Mootools to avoid any JS conflicts. I doubt they'll conflict anymore though. Will test & verify and if there are no issues, I'll strip it off the plugin code.
