### ISSUE TITLE
Allvideos feed output issue

### ISSUE THREAD

**Issue by shigri20** [joomlaworks/allvideos#22]
i using Allvideo +k2, after upgrading to joomla 3 i am facing feed issue. in categories that have video, feed can not show video and show bellow massage :

>  You  may not be able to visit this page because of:
an out-of-date bookmark/favouritea search engine that has an out-of-date listing for this sitea mistyped addressyou have no access to this pageThe requested resource was not found.An error has occurred while processing your request.
Please try one of the following pages:
Home Page
If difficulties persist, please contact the System Administrator of this site and report the error below.
Category not found

**I just check into feed output and find issue in linking videos check this output**

` <?xml version="1.0" encoding="utf-8"?>

<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
	<channel>
		<title>SUCH TV - SUCH TV - Videos</title>
		<description><![CDATA[Covering Breaking and latest News updates in politico-socio-economic, Sports, Tech, Health, weather & entertainment etc, from Pakistan and Worldwide.]]></description>
		<link>http://www.suchtv.pk</link>
		<lastBuildDate>Thu, 28 Jan 2016 14:33:18 +0500</lastBuildDate>
		<generator>SuchTv News Portal</generator>
		<atom:link rel="self" type="application/rss+xml" href="http://www.suchtv.pk/videos.feed?type=rss"/>
		<language>en-gb</language>
			<item>
			<title>News Bulletin 09am January 24, 2016</title>
			<link>http://www.suchtv.pk/videos/item/32703-news-bulletin-09am-january-24-2016.html</link>
			<guid isPermaLink="true">http://www.suchtv.pk/videos/item/32703-news-bulletin-09am-january-24-2016.html</guid>
			<description><![CDATA[<div class="K2FeedImage"><img src="http://www.suchtv.pk/media/k2/items/cache/461ea866dc5d9c88bcc4bf44068c2c5b_M.jpg" alt="News Bulletin 09am January 24, 2016" /></div><div class="K2FeedIntroText"></div><div class="K2FeedVideo">

<div class="avPlayerWrapper avVideo">
	<div class="avPlayerContainer">
		<div id="AVPlayerID_0_12b38e9cf3db82b2eea734ba13d00806" class="avPlayerBlock">
			<iframe src="http://www.suchtv.pk///www.dailymotion.com/embed/video/x3o3u7l" width="400" height="300" frameborder="0" allowfullscreen title="JoomlaWorks AllVideos Player"></iframe>					</div>
	</div>
</div>

</div>]]></description>
			<author>admin.web@suchtv.pk (Bilal)</author>
			<category>Videos</category>
			<pubDate>Sun, 24 Jan 2016 13:26:53 +0500</pubDate>
		</item>
	</channel>
</rss>
`
Check source in "iframe src="http://www.suchtv.pk///www.dailymotion.com/embed/video/x3o3u7l" my website url was add in video url. i facing this issue just on rss/feed
how can solve

**Comment by shigri20** [comment]
just check this url : http://www.suchtv.pk/videos.feed

**Comment by kavadas** [comment]
I verify the issue. Joomla! thinks no protocol URLs are relative links and prepends the site URL to them. In order to fix the issue we can use HTTPS protocol for all video providers.

**Comment by fevangelou** [comment]
Fixed in https://github.com/joomlaworks/allvideos/commit/5f5e76f3ed245304104008d5303c768ee519e505
