### ISSUE TITLE
php7 notice: deprecated constructor 

### ISSUE THREAD

**Issue by 810** [joomlaworks/allvideos#24]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgContentJw_sigpro has a deprecated constructor in /plugins/content/jw_sigpro/jw_sigpro.php on line 19

Also for the allvideos plugin line 18, but today i don't see that error, only for sigpro

Other notices for your components/plugins:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Services_JSON has a deprecated constructor /administrator/components/com_k2/lib/JSON.php on line 127

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Services_JSON_Error has a deprecated constructor in //administrator/components/com_k2/lib/JSON.php on line 794

**Comment by fevangelou** [comment]
Fixed in the repo, try the zip file from https://github.com/joomlaworks/allvideos/archive/master.zip

**Comment by 810** [comment]
seems to be ok now. other plugins need to be updated also

**Comment by chanatgo** [comment]
What plugin?
