### ISSUE TITLE
Declaration of JWElement::render() should be compatible with JFormField

### ISSUE THREAD

**Issue by vagnernogueira** [joomlaworks/allvideos#25]
PHP WARNING

Strict Standards: Declaration of JWElement::render() should be compatible with JFormField::render($layoutId, $data = Array) in /home/xxxxx/public_html/plugins/content/jw_allvideos/jw_allvideos/includes/elements/base.php on line 17

**Comment by fevangelou** [comment]
Using Joomla 3.5, right?

**Comment by jmcguirl** [comment]
I am using  3.6.2 and getting this error. Could you please share the resolution?

**Comment by UpekshaSilva** [comment]
same problem arise. Could you please share any solution with us?

**Comment by AlainRnet** [comment]
Hi!
Same problem J!3.6.5 :
`Strict Standards: Declaration of JWElement::render() should be compatible with JFormField::render($layoutId, $data = Array) in /web/plugins/content/jw_allvideos/jw_allvideos/includes/elements/base.php on line 17`

**Comment by dblaq** [comment]
Are you guys getting also a Fatal Error about cannot redeclare classes?

**Comment by fevangelou** [comment]
@amendoncabh This has been resolved for a long time now. Check the latest version of AllVideos please.
