### ISSUE TITLE
Veoh videos

### ISSUE THREAD

**Issue by genesisfan** [joomlaworks/allvideos#29]
Hi, Veoh videos will not shown with AllVideos 4.7.0.
Not with the 'use online video service id' or with the 'embed' option in Joomla! 3.5.1 and K2 2.7.0.

regards

**Comment by kricore** [comment]
Hello, I know I have already answered this on the forum but I'll provide some context here as well.
Veoh does not support https, so if your site is on https then videos from veoh.com are treated as mixed content thus being blocked in most browsers.
