### ISSUE TITLE
PHP Error on PHP version 7.x

### ISSUE THREAD

**Issue by genesisfan** [joomlaworks/allvideos#31]
I receive this PHP error when Allvideos is loaded on PHP version 7.x:

`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgContentJw_allvideos has a deprecated constructor in /home/domain/plugins/content/jw_allvideos/jw_allvideos.php on line 18`

**Comment by AyelGoth** [comment]
I confirm the existence of this error. In the Joomla 3.7 installation I also have the same error

**Comment by fevangelou** [comment]
v4.8.0 will be released the coming Monday, resolving any such issues. You can try it now by grabbing this file: https://github.com/joomlaworks/allvideos/archive/master.zip
