### ISSUE TITLE
feature request - set max-width and margins

### ISSUE THREAD

**Issue by shoulders** [joomlaworks/allvideos#32]
in the day of responsive youtube videos can exapand to much and look huge. So being able to set max-width allow me to keep the responsive behaviour but not got massive

the margins allow me to make things look nicer. This might need to be changed to padding (or both) to allow me to set the video to align left rather than centered (if possible)

**Comment by shoulders** [comment]
i added this code to my copy of All videos and it works well. When you set the following setting in the plugin admin the youtube responsive tyle will use this as max-width

- Default width (in px) for videos

I dont think i did it for height but i might of. cant remmember.

Do you want the code?

**Comment by fevangelou** [comment]
Can you make a PR from the latest snapshot of the repo?

**Comment by shoulders** [comment]
I have no idea how to do that, still learning GitHub. Sorry not being lazy.

What I can do is get the code I changed and add it here a snippet or attach a file. I dont think it was a lot.

**Comment by shoulders** [comment]
in the file  allvideos/plugin/jw_allvideos/tmpl/Responsive/default.php 

I altered the line
````
<div class="avPlayerContainer">
````
to
````
<div class="avPlayerContainer" style="max-width:<?php echo $output->playerWidth; ?>px;">
````

**Comment by fevangelou** [comment]
OK, I'll add it as an option in the next release. Makes sense.

**Comment by fevangelou** [comment]
Added in v5.0.0 which is coming out in the next 24 hours.

**Comment by fevangelou** [comment]
v5.0.0 is ready. The release blog post will be published tomorrow. If you wish to checkout the new version, just install directly in Joomla using this URL: https://github.com/joomlaworks/allvideos/archive/master.zip
