### ISSUE TITLE
Error loading media: File could not be played

### ISSUE THREAD

**Issue by dhyano** [joomlaworks/allvideos#33]
Hello

I installed allvideos, did all the config, loaded video on server under:
/images/stories/videos/voicing

"Local Video Folder" parameter is set to images/stories

And this is the code in the Joomla article:
{mp4}voicing/4{/mp4}

4 is the name of the video.

When I open the URL where the video is, I can see the video screen and when I click to play I get "Error loading media: File could not be played"

See attached pic.

Any ideas what I missed?
Thank you
Dhyano
![untitled](https://cloud.githubusercontent.com/assets/24719272/22182768/c9b21534-e0ad-11e6-809f-e6077c3006ca.jpg)

**Comment by fevangelou** [comment]
You need to add: {mp4}videos/voicing/4{mp4} because the root video path 
is /images/stories, not images/stories/videos ;)

F.
