### ISSUE TITLE
Facebook as Online Video Service

### ISSUE THREAD

**Issue by klausveliu** [joomlaworks/allvideos#34]
Hello,
I used your plugin very often, but I have found the lack of the feature of embedding the facebook videos.
Are you still developing this plugin anymore, so I can wait for an update?!

Here you can see an old request of mine.
http://www.joomlaworks.net/forum/allvideos/45604-facebook-as-online-video-service

Thank you!

**Comment by kricore** [comment]
I' ll +1 this.

**Comment by klausveliu** [comment]
I have tried to modify the plugin core myself, but with no success.
There the logic that I tried was from this plugin https://wordpress.org/plugins/facebook-video-embed
maybe this will help you to find an easy way to add the new feature.

**Comment by kricore** [comment]
This is a crude implementation but it seems to do the trick https://github.com/joomlaworks/allvideos/commit/a781befe3c5ac22def6c71a9aebe6db910edcaf6

**Comment by klausveliu** [comment]
Hello,
I have commented here, but maybe you have not been notified for my comment.
https://github.com/joomlaworks/allvideos/commit/a781befe3c5ac22def6c71a9aebe6db910edcaf6
Thank you.

**Comment by fevangelou** [comment]
Added in 4.8.x.
