### ISSUE TITLE
X-XSS Protection errors.

### ISSUE THREAD

**Issue by mixahlos** [joomlaworks/allvideos#38]
These errors are repeated in the console for every video in the page.

Error parsing header X-XSS-Protection: 1; mode=block; report=<URL>: insecure reporting URL for secure page at character position 22. The default protections will be applied.
Error parsing header X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube: insecure reporting URL for secure page at character position 22. The default protections will be applied.

**Comment by fevangelou** [comment]
I see they've added a new attribute on their embed code which I've added on AllVideos 4.8.2 as well. This is not the final release, but you can test it out and see if it solves these warnings: https://github.com/joomlaworks/allvideos/archive/master.zip

**Comment by mixahlos** [comment]
Thank you for the quick response Foti @fevangelou 
But I get exactly the same errors + new warnings "Unrecognized feature: 'autoplay'."

**Comment by fevangelou** [comment]
Then perhaps it's a feature under development... The embed tag (iframe) produced by AllVideos is the one that YouTube officially provides.

Can you provide a URL to your site/page so I can check as well?

**Comment by mixahlos** [comment]
Sure,
https://training.artenprise.eu/en/training-area/module-1-marketing/1-storytelling

euxaristw

**Comment by fevangelou** [comment]
Yeap, the embed is all good. So it's probably a temp issue with YouTube.

**Comment by mixahlos** [comment]
Thank you Foti.
