### ISSUE TITLE
Render blocking scripts  -- issue further clarified

### ISSUE THREAD

**Issue by drlukacs** [joomlaworks/allvideos#39]
The plugin loads a number of "render blocking" scripts:
-     plugins/content/jw_allvideos/jw_allvideos/includes/js/behaviour.js?v=4.8.0
-     plugins/content/jw_allvideos/jw_allvideos/includes/js/wmvplayer/silverlight.js?v=4.8.0
-     plugins/content/jw_allvideos/jw_allvideos/includes/js/wmvplayer/wmvplayer.js?v=4.8.0
-     plugins/content/jw_allvideos/jw_allvideos/includes/js/quicktimeplayer/ac_quicktime.js?v=4.8.0
-     plugins/content/jw_allvideos/jw_allvideos/includes/js/jwplayer/jwplayer.js?v=4.8.0

Even when compression is turned on, there will be several files generated:

-     plugins/content/jw_allvideos/jw_allvideos/includes/js/jwp.js.php?v=4.8.0
-     plugins/content/jw_allvideos/jw_allvideos/includes/js/jwplayer/jwplayer.js

These scripts are **render blocking**: they delay the rendering of the page, because they are currently **not marked** as _deferred_.

An option should be added to mark the scripts as "deferred."

**Comment by fevangelou** [comment]
Do not cross post please. I've given you my answer already.
