### ISSUE TITLE
Audio tags not rendered in category item view

### ISSUE THREAD

**Issue by kbrookes** [joomlaworks/allvideos#41]
Using v5.0 of AllVideos, K2 2.9.1 and Joomla 3.9.11 - audio tags aren't rendering in CatItem view, only in item view.

Not sure if this is expected behaviour or not.

**Comment by fevangelou** [comment]
There is no filter for HTML tags in either AllVideos or K2. So something else is wrong here... Check if plugins are enabled in listings in K2 and that you're not stripping out any HTML tags in content. Additionally, if word limit is enabled, the strip tags takes effect so nothing would display either way.

**Comment by kbrookes** [comment]
Thanks Fotis,

Turns out it was a PEBKAC error. 

K2 plugins was on, no filtering, no word limit - but media was off.

So it was showing the tag, but not loading the player. Silly mistake. Sorry about that.
