### ISSUE TITLE
GDPR compliance - 2Click solution ?

### ISSUE THREAD

**Issue by pepperstreet** [joomlaworks/allvideos#43]
Hello, is it possible to add a 2-click solution into your AllVideos plugin? Or do you have any future plans in this regard? I have read the related article about the web357 cookie plugin integration, which is pretty cool, but I have a client inquiry where the homepage does not need any cookie consent plugin. They have some yt videos, and I don't see the necessity to implement a cookie tool and banner for that single purpose. IMHO, a 2-click solution would be light and easy. 

Thanks in advance.

**Comment by fevangelou** [comment]
You do know there's an option in the plugin to load videos from YouTube without any tracking, right?

It's called "Enable YouTube privacy-enhanced mode".

**Comment by pepperstreet** [comment]
Yes, I know. But I have read many articles about this type of embed... and the German articles and discussions give the advice to add a 2-click solution as well. There are also WP plugins that seem to solve it this way.

**Comment by pepperstreet** [comment]
Also "privacy-enhanced" seem to be related to the doubleClick network... and/or the related videos that are offered at the end. The server connection and the IP is stored anyway... maybe other things too!?

**Comment by fevangelou** [comment]
AllVideos is meant to be a player. There's no need to integrate any GDPR-related or other user-consent related options. In most cases, it should be sufficient to use a single such option for the entire site (e.g. something like QuantCast's user consent if it's a media site).

**Comment by pepperstreet** [comment]
Yep, I understand your position and opinion. But there are also other Player Plugins that implement this minimal 2-click feature. Since my client uses K2, SIG and ALLVIDEOS for a product catalog, they are used to the AllVideos integration... and I wonder why and how the GDPR issue could be solved. I don't want them to remove all the videos... just to install and implement another PLUGIN, which uses another content plugin syntax etc. 
It would be sleek and easy to stay with ALLVIDEOS.

**Comment by fevangelou** [comment]
Unlike other extensions, at least you know you can override AllVideos. And so you can try this: https://www.web357.com/blog/news/how-to-block-cookies-from-video-providers-like-youtube

**Comment by pepperstreet** [comment]
Yes, I know the article. Smart solution. Like a combination of a site-wide consent cookie to enable the video playback. Actually I like this one, but it requires the extra commercial web357 plugin. In the end, I would have a cookie extension... which is for video display only. Not sure the client, or the users would like that. IMHO, the simple 2-click is much easier and understandable for novice people. 

The override / template feature is cool. Do you think a 2-click solution could be added this way?

**Comment by pepperstreet** [comment]
FYI – this seem to be a system plugin (no player, no shortcodes). It retrieves embedded videos as far as I understand it. Would it work with and modify AllVideos embeds as well!? 
https://extensions.joomla.org/extension/jmg-youtube-dsgvo/

**Comment by fevangelou** [comment]
What you ask should normally be directed to the forum. I can't provide any further assistance, sorry.
