### ISSUE TITLE
Height of video not correct

### ISSUE THREAD

**Issue by genesisfan** [joomlaworks/allvideos#8]
Hi JoomlaWorks,
Hopefully you can help me out with this allvideo problem. The height of the video is totally wrong! See my backup site: http://bit.ly/1EMo0Z4. I used {youtube}2mBov0lUktM|640|360{/youtube} but it's not 360...?
![allvideo001](https://cloud.githubusercontent.com/assets/1644862/5061376/658ab3da-6d92-11e4-9bfa-f599e2576292.jpg)

Regards,
GenesisFan

**Comment by fevangelou** [comment]
Sorry for the late but I assume you were using the "Responsive" layout while attempting to adjust the dimensions, correct?

**Comment by genesisfan** [comment]
Yes, I'm using a responsive layout.

**Comment by fevangelou** [comment]
In this case, since the width is switched to 100%, if you specify a height option, it will only mess up the video's proportions. The responsive layout will make any video fit its container, so the additional width/height params are not needed. Check it out and let me know.

**Comment by genesisfan** [comment]
I've contacted last November also Gavick, the Joomla Template builder. They came with the solution:

The problem is caused by your Custom CSS code - please remove:
```height: 100%!important;```

from the following selectors in the template.css file:
```.avVideo .avPlayerContainer .avPlayerBlock iframe, .avVideo .avPlayerContainer .avPlayerBlock object, .avVideo .avPlayerContainer .avPlayerBlock embed, .avVideo .avPlayerContainer .avPlayerBlock > div```

Regards
